name: p4templates - scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    name: MEND scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Mend scan
      run: |
        echo resolveAllDependencies=False > ${{ github.workspace }}/MEND.config
        echo python.resolveDependencies=True >> ${{ github.workspace }}/MEND.config
        echo python.path=python3 >> MEND.config
        docker pull perforce/ubuntu22-mend
        docker run -v ${{ github.workspace }}:/scan \
        perforce/ubuntu22-mend bash -c "
        java -jar /opt/white-source/wss-unified-agent.jar \
        -c /scan/MEND.config \
        -d /scan \
        -project p4templates-main \
        -product p4templates \
        -apiKey ${{ secrets.MEND_API_KEY }} \
        -userKey ${{ secrets.MEND_USER_KEY }} \
        -wss.url ${{ secrets.MEND_URL }}"
